# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 08d43800d0c838559ba74cc1f5400d31f14732607ba39fb9f32832b232f9b7408fd95c0408c42662d4f0eb814545cde66851a055f7df9a1bb1ea62b088ab9a4c

test:
  secret_key_base: 856a575a7c54bdfe3601e75d7a0456780c1361bfce8e4a92503a2700958b8a1567ea0f0bc4fe76ebeed2aec6c1ef4f54437a25f6a3723394857f4f28f4a6d3b0

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
